
[platformio]
default_envs = drone
boards_dir = boards

; ---------------------------------------------------------------------------
[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rp2350
framework = arduino
board_build.core = earlephilhower

board_build.filesystem_size = 1m

monitor_speed = 115200
build_flags =
    -DUSB_MANUFACTURER='"LSwarm"'
    -DUSB_PRODUCT='"Mk.1"'
    -DPICO_XOSC_STARTUP_DELAY_MULTIPLIER=64
    -O2

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3

[env:drone]
build_flags = ${env.build_flags}

[env:esp_passthrough]
build_flags = ${env.build_flags} -DESP_PASSTHROUGH_ONLY=1

[env:drone_debug]
build_flags = ${env.build_flags} -DDEBUG_BUILD=1 -g -Og
build_type = debug
upload_protocol = cmsis-dap
debug_tool  = cmsis-dap